### ISSUE TITLE
Downloaded Zip Contains Only .ldf File, .mdf File Missing

### ISSUE THREAD

**Issue by NMounikaa** [fekberg/csharp-data-access-fundamentals#1]
Issue with .ldf file

I downloaded the zip folder from this GitHub but it only contains the .ldf file. Could you please provide the .mdf file as well?

Thank you!

**Comment by fekberg** [comment]
Thanks for letting me know it was missing. I have added this now!

**Comment by NMounikaa** [comment]
Thank you for adding the .mdf file! Really appreciate your quick response
